"""Add new_field book_value_per_share

Revision ID: a647eed9834f
Revises: 5749dc3f2522
Create Date: 2023-09-28 00:22:38.119006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a647eed9834f'
down_revision = '5749dc3f2522'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_data', sa.Column('book_value_per_share', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('financial_data', 'book_value_per_share')
    # ### end Alembic commands ###
