"""Add new_field to Item model

Revision ID: c329cf028056
Revises: 
Create Date: 2023-09-07 18:08:46.427135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c329cf028056'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_data', sa.Column('face_value', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('financial_data', 'face_value')
    # ### end Alembic commands ###
